#pull image
FROM node:18.4.0-alpine
#set working directory
WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH


#install dependencies 
COPY package.json ./
COPY yarn.lock ./
RUN npm install -g yarn@latest --force

COPY . ./

CMD ["yarn", "start"]