version: '3'

services:
#  frontend:
#    container_name: et_frontend
#    build: 
#      context: ./frontend
#      dockerfile: dockerfile
#    volumes:
#      - './frontend:/frontend'
#      - './frontend/node_modules'
#    ports:
#      - '3000:3000'
#    environment:
#      - CHOKIDAR_USEPOLLING=true
     
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  backend:
    container_name: et_backend
    build: 
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - '8000:80'