FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /app

COPY *.sln .
COPY Backend.DAL_EF/*.csproj ./Backend.DAL_EF/
COPY Backend.Services/*.csproj ./Backend.Services/
COPY Backend.webapi/*.csproj ./Backend.webapi/
COPY Backend.TestProject/*.csproj ./Backend.TestProject/
COPY Backend.Shared/*.csproj ./Backend.Shared/

RUN dotnet restore

COPY Backend.DAL_EF/. ./Backend.DAL_EF/
COPY Backend.Services/. ./Backend.Services/
COPY Backend.webapi/. ./Backend.webapi/
COPY Backend.TestProject/. ./Backend.TestProject/
COPY Backend.Shared/. ./Backend.Shared/



WORKDIR /app
RUN dotnet publish -c Release -o out

FROM ubuntu:focal as runtime
WORKDIR /app

RUN apt-get update 
RUN apt-get install -y curl

RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 6.0 -Runtime dotnet -InstallDir /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
#RUN dotnet-install
#COPY Backend.DAL_EF/. ./Backend.DAL_EF/
#RUN dotnet tool install --global dotnet-ef
#ENV PATH $PATH:/root/.dotnet/tools

COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "Backend.webapi.dll"]
